### ISSUE TITLE
Setup Time

### ISSUE THREAD

**Issue by tracyddsheng** [cse403-fitquest/fitquest#79]
The time it takes for setup is rather long but I do understand there are certain limitations right now. I am just wondering if maybe there is a way to streamline it a little more especially with having to input your own data? From what I saw in your demo though the app seems great and I'm excited to see it in action.

**Comment by afutofu** [comment]
Hi Tracy, thanks for your feedback. Which part of the setup took the longest for you? Knowing that will help us identify which parts to streamline if possible.

**Comment by afutofu** [comment]
Hi Tracy, the Android studio part is inevitable yes. However the Firebase setup is completely optional if you want to use your own data as mentioned in the README before. I've made changes to the README so that its much clearer in the setup that it is optional and you can totally run the app without having to setup your own firebase project.

**Comment by afutofu** [comment]
Was there an error code given in the terminal or on the emulator? Did you use an Android device on Expo Go? Usually pressing "r" (which reloads any app connected) on the terminal after `npm start` fixes the problem. Also ensure that your device (laptop, pc, mac) from when you're running the `npm start` command and your phone (if you're using an Android) are on the same network.
